!
! Row ID: {{ID}}
!
!
! Config for B2B VPN for Customer {{CUSTOMER_NAME}}
!
!
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN remark {{CUSTOMER_NAME}} - {{CUSTOMER_CONTACT}}
{%- if HOST_INTERESTING_CIDR_1 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_1_IP}} {{HOST_INTERESTING_CIDR_1_NETMASK}} {{CUST_INTERESTING_CIDR_1_IP}} {{CUST_INTERESTING_CIDR_1_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_2 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_2_IP}} {{HOST_INTERESTING_CIDR_2_NETMASK}} {{CUST_INTERESTING_CIDR_2_IP}} {{CUST_INTERESTING_CIDR_2_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_3 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_3_IP}} {{HOST_INTERESTING_CIDR_3_NETMASK}} {{CUST_INTERESTING_CIDR_3_IP}} {{CUST_INTERESTING_CIDR_3_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_4 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_4_IP}} {{HOST_INTERESTING_CIDR_4_NETMASK}} {{CUST_INTERESTING_CIDR_4_IP}} {{CUST_INTERESTING_CIDR_4_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_5 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_5_IP}} {{HOST_INTERESTING_CIDR_5_NETMASK}} {{CUST_INTERESTING_CIDR_5_IP}} {{CUST_INTERESTING_CIDR_5_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_6 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_6_IP}} {{HOST_INTERESTING_CIDR_6_NETMASK}} {{CUST_INTERESTING_CIDR_6_IP}} {{CUST_INTERESTING_CIDR_6_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_7 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_7_IP}} {{HOST_INTERESTING_CIDR_7_NETMASK}} {{CUST_INTERESTING_CIDR_7_IP}} {{CUST_INTERESTING_CIDR_7_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_8 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_8_IP}} {{HOST_INTERESTING_CIDR_8_NETMASK}} {{CUST_INTERESTING_CIDR_8_IP}} {{CUST_INTERESTING_CIDR_8_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_9 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_9_IP}} {{HOST_INTERESTING_CIDR_9_NETMASK}} {{CUST_INTERESTING_CIDR_9_IP}} {{CUST_INTERESTING_CIDR_9_NETMASK}}
{%- endif %}
{%- if HOST_INTERESTING_CIDR_10 is defined %}
access-list Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN permit ip {{HOST_INTERESTING_CIDR_10_IP}} {{HOST_INTERESTING_CIDR_10_NETMASK}} {{CUST_INTERESTING_CIDR_10_IP}} {{CUST_INTERESTING_CIDR_10_NETMASK}}
{%- endif %}
!
{%- if VPN_TOPOLOGY == "Single-Homed" %}
tunnel-group {{CUST_VPN_GW_1}} type ipsec-l2l
tunnel-group {{CUST_VPN_GW_1}} ipsec-attributes
 {{VPN_PHASE1}} pre-shared-key {{VPN_PSK}}
 isakmp keepalive threshold 3600 retry 2
!
{% if CUST_VPN_GW_2 is defined %}
tunnel-group {{CUST_VPN_GW_2}} type ipsec-l2l
tunnel-group {{CUST_VPN_GW_2}} ipsec-attributes
 {{VPN_PHASE1}} pre-shared-key {{VPN_PSK}}
 isakmp keepalive threshold 3600 retry 2
!
{% endif %}
{%- endif %}

{%- if VPN_TOPOLOGY == "Multi-Homed"%}
tunnel-group {{CUST_VPN_GW_1}} type ipsec-l2l
tunnel-group {{CUST_VPN_GW_1}} ipsec-attributes
 {{VPN_PHASE1}} pre-shared-key {{VPN_PSK}}
 isakmp keepalive threshold 3600 retry 2
!
{%- endif %}
!
crypto map Outside_map {{VPN_SEQ_NUMBER}} match address Outside_cryptomap_{{VPN_SEQ_NUMBER}}_{{CUSTOMER_NAME_ACL}}_VPN
{%- if VPN_TOPOLOGY == "Singe-Homed" %}
crypto map Outside_map {{VPN_SEQ_NUMBER}} set peer {{CUST_VPN_GW_1}}
{%- if CUST_VPN_GW_2 is defined %}
crypto map Outside_map {{VPN_SEQ_NUMBER}} set peer {{CUST_VPN_GW_2}}
{%- endif %}
{%- endif %}
{%- if VPN_TOPOLOGY == "Multi-Homed" %}
crypto map Outside_map {{VPN_SEQ_NUMBER}} set peer {{CUST_VPN_GW_1}}
{%- endif %}
crypto map Outside_map {{VPN_SEQ_NUMBER}} set {{VPN_PHASE1}} transform-set {{VPN_PHASE2}}
crypto map Outside_map {{VPN_SEQ_NUMBER}} set security-association lifetime seconds 28800
crypto map Outside_map {{VPN_SEQ_NUMBER}} set nat-t-disable
!



